# Use Python image
FROM python:3.10

# Set working directory
WORKDIR /app

# Copy files
COPY . /app

# Install dependencies
RUN pip install --no-cache-dir flask nltk scikit-learn

# Download nltk data
RUN python -m nltk.downloader punkt stopwords

# Expose port
EXPOSE 5000

# Run app
CMD ["python", "app.py"]